### ISSUE TITLE
error: 'SeqFileIn' was not declared in this scope

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan#995] opened 2015-05-11 18:10 UTC
Hi all.

SeqAn-2.0.0
cmake-3.0.2
Fedora 21 x86_64

SeqAn's building configuration:

```
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro  -lrt'
+ export LDFLAGS
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON '-DCMAKE_C_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic' '-DCMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DSEQAN_ENABLE_DEBUG=0 -DSEQAN_ENABLE_TESTING=0 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_INCLUDE_PATH:STRING=/usr/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2 -DSEQAN_BUILD_SYSTEM:STRING=SEQAN_RELEASE -DCMAKE_BUILD_TYPE:STRING=Release -DSEQAN_HAS_BZIP2=1 -DSEQAN_HAS_ZLIB=1 -DSEQAN_APP_VERSION:STRING=2.0.0 -DBZIP2_INCLUDE_DIR:PATH=/usr/include '-DBZIP2_LIBRARY:FILEPATH=-L/usr/lib64 -lbz2' -DZLIB_INCLUDE_DIR:PATH=/usr/include '-DZLIB_LIBRARY:FILEPATH=-L/usr/lib64 -lz' -DBoost_INCLUDE_DIR:PATH=/usr/include -DYARA_ARCH_NATIVE:BOOL=ON -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE ../..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Initializing SeqAn Build System...
-- No revision system found.
--   Repository date not determined.
--   Repository revision not determined.
-- Configuring demos
-- Configuring demos
-- Configuring apps
-- Configuring apps
-- Configuring apps/stellar
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
--   Determined version is 1.4.2
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.8") 
-- Configuring apps/searchjoin
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Configuring apps/dfi
-- Configuring apps/rep_sep
-- Configuring apps/sak
-- Looking for BZ2_bzCompressInit in -L/usr/lib64 -lbz2
-- Looking for BZ2_bzCompressInit in -L/usr/lib64 -lbz2 - found
-- Configuring apps/razers3
-- Performing Test CXX11_FOUND
-- Performing Test CXX11_FOUND - Success
-- Configuring apps/sgip
-- Configuring apps/seqcons
-- Configuring apps/splazers
-- Configuring apps/tree_recon
-- Configuring apps/razers
-- Configuring apps/ngs_roi
-- Configuring apps/param_chooser
-- Configuring apps/seqcons2
-- Configuring apps/samcat
-- Configuring apps/micro_razers
-- Configuring apps/seqan_tcoffee
-- Configuring apps/rabema
-- Configuring apps/sam2matrix
-- Configuring apps/pair_align
-- Configuring apps/yara
-- Configuring apps/razers2
-- Configuring apps/bs_tools
-- Boost version: 1.55.0
-- Configuring apps/fx_tools
-- Configuring apps/fiona
-- Boost version: 1.55.0
-- Configuring apps/alf
-- Configuring apps/snp_store
-- Boost version: 1.55.0
-- Configuring apps/gustaf
-- Configuring apps/insegt
-- Configuring apps/mason2
-- Configuring apps/seqan_flexbar
-- Configuring dox
-- Configuring manual
-- Found Sphinx: /usr/bin/sphinx-build 
-- Configuring util/py_lib
--   adding nosetests for seqan.dox
-- Found Java: /usr/bin/java (found version "1.8.0.45") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS_RELEASE
    CMAKE_Fortran_FLAGS_RELEASE
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SEQAN_ENABLE_DEBUG
    SEQAN_ENABLE_TESTING


-- Build files have been written to: /home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/build/Release
+ export 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic'
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic'
+ make
```

Stellar build fails with:
```
[  0%] Building CXX object apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o
cd /home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/build/Release/apps/stellar && /usr/lib64/ccache/c++   -DSEQAN_APP_VERSION=\"1.4.2\" -DSEQAN_DATE=\"\" -DSEQAN_ENABLE_TESTING=0 -DSEQAN_HAS_EXECINFO=1 -DSEQAN_REVISION=\"tarball\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic  -W -Wall -Wno-long-long -fstrict-aliasing -Wstrict-aliasing -pedantic -Wno-variadic-macros -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -DSEQAN_ENABLE_DEBUG=0   -o CMakeFiles/stellar.dir/stellar.cpp.o -c /home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp: In function 'bool _importSequences(const CharString&, const CharString&, seqan::StringSet<TString, seqan::Owner<> >&, seqan::StringSet<TString, seqan::Owner<> >&)':
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:240:5: error: 'SeqFileIn' was not declared in this scope
     SeqFileIn inSeqs;
     ^
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:241:15: error: 'inSeqs' was not declared in this scope
     if (!open(inSeqs, (toCString(fileName))))
               ^
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:253:19: error: 'inSeqs' was not declared in this scope
     for (; !atEnd(inSeqs); ++seqCount)
                   ^
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp: In function 'void _setParser(seqan::ArgumentParser&)':
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:503:42: error: 'INPUT_FILE' is not a member of 'seqan::ArgParseArgument'
     addArgument(parser, ArgParseArgument(ArgParseArgument::INPUT_FILE, "FASTA FILE 1"));
                                          ^
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:505:42: error: 'INPUT_FILE' is not a member of 'seqan::ArgParseArgument'
     addArgument(parser, ArgParseArgument(ArgParseArgument::INPUT_FILE, "FASTA FILE 2"));
                                          ^
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:567:74: error: 'OUTPUT_FILE' is not a member of 'seqan::ArgParseArgument'
     addOption(parser, ArgParseOption("o", "out", "Name of output file.", ArgParseArgument::OUTPUT_FILE));
                                                                          ^
/home/sagitter/rpmbuild/BUILD/seqan-b17b332d36a392446538bdf84058f8b8a3c9276a/apps/stellar/stellar.cpp:571:91: error: 'OUTPUT_FILE' is not a member of 'seqan::ArgParseArgument'
                                      "Name of output file for disabled query sequences.", ArgParseArgument::OUTPUT_FILE));
                                                                                           ^
apps/stellar/CMakeFiles/stellar.dir/build.make:57: recipe for target 'apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o' failed
make[2]: *** [apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o] Error 1
```

**Comment by rrahn** [comment] 2015-07-27 08:27
Hi, we will have a look at this. 
Is it only the stellar app that is failing? Or is this a general problem when calling make with all apps and tests?

**Comment by rrahn** [comment] 2015-08-13 13:14
@sagitter I just saw that your cmake call contained this value ```-DSEQAN_APP_VERSION:String=2.0.0```. I think you mixed it up with ```-DSEQAN_VERSION:String=2.0.0```.
However, I could not reproduce the error, so I will close the issue. 
If you still experience some problems with this please feel free to reopen it.

**Closed by rrahn** 2015-08-13 13:14 UTC
Labels: regression
