### ISSUE TITLE
Auto static linking against pthread for the Apps

### ISSUE THREAD

**Issue by temehi** [seqan/seqan#1926] opened 2016-11-09 16:28 UTC
Apps are built static by default through the Macro [`seqan_register_apps ()`](https://github.com/seqan/seqan/blob/develop/util/cmake/SeqAnBuildSystem.cmake#L139) under SeqAnBuildSystem.cmake. 
PR  #1878 fixed the problem for all other cases but this auto static thingy. 

It looks like  ` seqan_register_apps ()` comes after the[ if-check](https://github.com/seqan/seqan/blob/develop/util/cmake/FindSeqAn.cmake#L299) at FindSeqan.cmake. adding  `-Wl,--whole-archive -lpthread -Wl,--no-whole-archive` with the `-static` / `-static-libgcc` flags inside  `seqan_register_apps ()` seems to fix the issue

**Comment by h-2** [comment] 2016-11-10 12:14
Ah, thats true. It's a regression caused by #1884 

What we need to to do is move the static block from line 142 to line 313 in SeqAnBuildSystem.cmake

I will take it.

**Comment by h-2** [comment] 2016-12-09 14:45
fixed by #1960

**Closed by h-2** 2016-12-09 14:45 UTC
Labels: regression
