### ISSUE TITLE
chainSeedsGlobally assert

### ISSUE THREAD

**Issue by mchaisso** [seqan/seqan#2318] opened 2018-06-27 22:40 UTC
Hi, 
  I'm using chainSeedsGlobally to filter alignments.  Does the sdp implementation require that the start and end points of seeds be on the same diagonal? There are no issues when all seeds are diagonal, but   the following code asserts:

```terminal
./test.out 
seqan/include/seqan/seeds/seeds_global_chaining.h:281 Assertion failed : _checkScoreInvariant(intermediateSolutions) should be true but was 0

stack trace:
  0          [0x401860]  ./test.out()
  1          [0x402a88]  ./test.out()
  2          [0x4015ca]  ./test.out()
  3    [0x7f1bd60c2c05]  __libc_start_main + 0xf5
  4          [0x4013c9]  ./test.out()
```

```c++
#include <vector>
#include <iostream>
#include "seqan/seeds.h"
#include "seqan/align.h"

using namespace std;
int main() {

	seqan::SeedSet<seqan::Seed<seqan::Simple>, seqan::Unordered> simple;
	seqan::addSeed(simple, seqan::Seed<seqan::Simple>(1,  5, 10, 15), seqan::Single());
	seqan::addSeed(simple, seqan::Seed<seqan::Simple>(5,  9, 40, 34), seqan::Single());
	seqan::addSeed(simple, seqan::Seed<seqan::Simple>(40, 10, 45, 17), seqan::Single());

	seqan::String<seqan::Seed<seqan::Simple> > simpleChain;
	seqan::chainSeedsGlobally(simpleChain, simple, seqan::SparseChaining());
	cout << "Simple chain " << seqan::length(simpleChain) << endl;
}
```

**Comment by rrahn** [comment] 2018-06-28 06:16
Thanks for reporting. 
There are no requirements on the seeds in the set for the chaining algorithm. So this seems to be a bug. 
We'll will look into it.

**Comment by mchaisso** [comment] 2018-06-28 12:54
The two empty #include's were a copy and paste error. I'll also try and look into it.

**Comment by mchaisso** [comment] 2018-07-06 00:13
The code faithfully implements Gusfield's global chaining, and I think the
algorithm has an error in it. The list L is sorted by l_j, however they are
not in nondecreasing order of V_j, as shown by the seeds that were given in
the bug report, which triggers the assert statement. Also, considering
Figure 13.5 (p327), if you swap the 3 and 5 scores of the top two
rectangles, the box with weight 3 in the middle of the figure would have
the incorrect weight assigned to it. However with fixed lengths and
diagonal matches, the algorithm gives correct results.

**Comment by smehringer** [comment] 2018-08-01 13:48
Hi @mchaisso ,

unfortunately, I cannot reproduce your error. When I compile the minimal example that you stated above, it produces the result `Simple Chain 1`. I built this with the current master branch of seqan in release mode. Can you please give further information about the seqan version and other parameters you used?

To the algorithm in general: I strongly believe that the algorithm of Gusfield is correct although I'm no expert in this field.

> The list L is sorted by l_j, however, they are not in nondecreasing order of V_j, as shown by the seeds that were given in the bug report, which triggers the assert statement.

Yes, the list L is not sorted in any way by the values of ```V_(j)```, but this is not needed since the triplets `(l_j, V_j, j)` are updated in each iteration of the algorithm and only the triplet containing the maximum value reached so far is stored while lower ones are deleted. Thus the list L needs not to be sorted by V_j since low values are deleted. Does that make sense to you?

>Also, considering Figure 13.5 (p327), if you swap the 3 and 5 scores of the top two rectangles, the box with weight 3 in the middle of the figure would have the incorrect weight assigned to it.

I think the weights in the boxes in figure 13.5 are arbitrary weights of the seeds and have nothing to do with any values "assigned" to a triplet or intermediate result. So there can't be anything wrong.

If you have any further questions on the algorithm or feel that I might have understood you wrongly, feel free to ask and elaborate on this more.

**Comment by mchaisso** [comment] 2018-08-02 19:15
Can you try building in debug mode, or disabling NDEBUG? The invariant
asserts on this input.

Thanks,
-Mark

**Comment by smehringer** [comment] 2018-08-06 10:38
So sorry, of course in release mode nothing asserts :man_facepalming: 

I reproduced your error and found the bug. The Gusfield algorithm is correct but we got an if-clause wrong.

Thanks for catching this!

**Comment by smehringer** [comment] 2018-10-24 17:14
Hi @mchaisso
we merged several fixes for the chaining algorithm. Check out if it works for you.

**Closed by smehringer** 2018-10-24 17:14 UTC
Labels: bug
