### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan#830] opened 2015-02-05 18:23 UTC
Hi all.

Are there incompatibilities of the seqan-2.0.0-rc1's tests on ARM architectures?

```
[  9%] Building CXX object tests/parallel/CMakeFiles/test_parallel.dir/test_parallel.cpp.o
cd /builddir/build/BUILD/seqan-seqan-v2.0.0-rc1/build/Release/tests/parallel && /usr/bin/c++   -DSEQAN_ENABLE_TESTING=1 -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard  -W -Wall -Wno-long-long -fstrict-aliasing -Wstrict-aliasing -pedantic -Wno-variadic-macros -fopenmp -std=c++11 -I/builddir/build/BUILD/seqan-seqan-v2.0.0-rc1/include    -o CMakeFiles/test_parallel.dir/test_parallel.cpp.o -c /builddir/build/BUILD/seqan-seqan-v2.0.0-rc1/tests/parallel/test_parallel.cpp
{standard input}: Assembler messages:
{standard input}:10611: Error: bad instruction `rep'
```

Full log here: https://kojipkgs.fedoraproject.org//work/tasks/3293/8833293/build.log

**Comment by esiragusa** [comment] 2015-02-05 21:36
Hi @sagitter. I guess that most of the library could work out of the box, but the parallel primitives won't... Do all SeqAn 1.4.x tests compile on ARM?

**Comment by sagitter** [comment] 2015-02-06 21:09
SeqAn 1.4.x did not compile tests: https://kojipkgs.fedoraproject.org//packages/seqan/1.4.2/9.fc22/data/logs/armv7hl/build.log, this problem was not established. Or am I wrong?

**Comment by sagitter** [comment] 2015-02-07 22:55
Same problem during compilation of application searchjoin (on ARM only)
```
[  7%] Building CXX object apps/searchjoin/CMakeFiles/s4_join.dir/join.cpp.o
cd /builddir/build/BUILD/seqan-seqan-v2.0.0-rc1/build/Release/apps/searchjoin && /usr/bin/c++   -DSEARCHJOIN_HUGEDB=TRUE -DSEQAN_DATE=\"\" -DSEQAN_ENABLE_TESTING=0 -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP=1 -DSEQAN_REVISION=\"\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -W -Wall -Wno-long-long -fstrict-aliasing -Wstrict-aliasing -pedantic -Wno-variadic-macros -fopenmp -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -DSEQAN_ENABLE_DEBUG=0 -I/builddir/build/BUILD/seqan-seqan-v2.0.0-rc1/include    -o CMakeFiles/s4_join.dir/join.cpp.o -c /builddir/build/BUILD/seqan-seqan-v2.0.0-rc1/apps/searchjoin/join.cpp
{standard input}: Assembler messages:
{standard input}:16249: Error: bad instruction `rep'
{standard input}:16308: Error: bad instruction `rep'
```
Full log: https://kojipkgs.fedoraproject.org//work/tasks/1212/8861212/build.log

**Comment by sagitter** [comment] 2016-07-13 19:20
`searchjoin` app from `seqan-2.2.0` does not compile with same error of this ticket:

```
[ 83%] Building CXX object apps/searchjoin/CMakeFiles/s4_search.dir/search.cpp.o
cd /builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release/apps/searchjoin && /usr/bin/c++   -DSEARCHJOIN_HUGEDB=TRUE -DSEQAN_APP_VERSION=\"0.5.4\" -DSEQAN_DATE=\"\" -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP=1 -DSEQAN_REVISION=\"tarball\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/builddir/build/BUILD/seqan-seqan-v2.2.0/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -fPIC   -W -Wall -pedantic -fstrict-aliasing -Wstrict-aliasing -fopenmp -DNDEBUG    -DSEQAN_GLOBAL_EXCEPTION_HANDLER=1 -o CMakeFiles/s4_search.dir/search.cpp.o -c /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/searchjoin/search.cpp
In file included from /builddir/build/BUILD/seqan-seqan-v2.2.0/include/seqan/basic/basic_allocator.h:47:0,
                 from /builddir/build/BUILD/seqan-seqan-v2.2.0/include/seqan/basic.h:74,
                 from /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/searchjoin/search.cpp:58:
/builddir/build/BUILD/seqan-seqan-v2.2.0/include/seqan/basic/basic_simd_vector.h:53:3: warning: #warning is a GCC extension
  #warning "No supported platform for SIMD vectorization!"
   ^~~~~~~
/builddir/build/BUILD/seqan-seqan-v2.2.0/include/seqan/basic/basic_simd_vector.h:53:3: warning: #warning "No supported platform for SIMD vectorization!" [-Wcpp]
{standard input}: Assembler messages:
{standard input}:171632: Error: bad instruction `rep'
{standard input}:171752: Error: bad instruction `rep'
{standard input}:320254: Error: bad instruction `rep'
{standard input}:320606: Error: bad instruction `rep'
apps/searchjoin/CMakeFiles/s4_search.dir/build.make:65: recipe for target 'apps/searchjoin/CMakeFiles/s4_search.dir/search.cpp.o' failed
```

**Comment by h-2** [comment] 2016-07-13 20:50
@sagitter Does deactivating SIMD fix it? Can you reproduce the problem with a library test? The apps are not our priority right now and ARM is not officially supported platform -- but we do accept patches of course and will try to fix this, if it isn't a big problem.

**Comment by sagitter** [comment] 2016-07-14 10:03
>@sagitter Does deactivating SIMD fix it?

How i can deactive it ?

>The apps are not our priority right now and ARM is not an officially supported platform -- but we do accept patches of course and will try to fix this, if it isn't a big problem.

it's not a great problem at the moment. I still must keep `seqan-1.4.2` (that builds with ARMs) on Fedora since it's a dependency of other software. But sooner or later I have to decide if fixing this problem or excluding ARM builds of `Seqan-2.*`

**Comment by rrahn** [comment] 2016-07-14 10:07
@sagitter I am currently preparing a patch to exclude Simd related paths if the architecture is not supported. The builds should than run through. 🙏

**Comment by rrahn** [comment] 2016-07-14 15:12
@sagitter can you try this branch if it works now?
https://github.com/rrahn/seqan/tree/fix/simd_detection

**Comment by sagitter** [comment] 2016-07-14 16:13
I have patched `seqan-2.2.0` with https://github.com/rrahn/seqan/commit/f48d8a87015caf13893a944683737ea0e5b114ef: failed for missing header file

Build log: https://kojipkgs.fedoraproject.org//work/tasks/6146/14896146/build.log

**Comment by rrahn** [comment] 2016-07-14 17:32
Oh, probably because of this line:
https://github.com/rrahn/seqan/commit/f48d8a87015caf13893a944683737ea0e5b114ef#diff-3c8fb397c5ac5a2dd5e446fa57153c21R46
Can you change the line to:
```cpp
#if !defined(__arm__) && !defined(_M_ARM)
...
```
and try again?

**Comment by rrahn** [comment] 2016-07-14 17:33
So replace the || with &&.

**Comment by sagitter** [comment] 2016-07-14 20:05
>Oh, probably because of this line:
rrahn@f48d8a8#diff-3c8fb397c5ac5a2dd5e446fa57153c21R46
Can you change the line to:
#if !defined(__arm__) && !defined(_M_ARM)
...
and try again?


```
[ 83%] Building CXX object apps/searchjoin/CMakeFiles/s4_search.dir/search.cpp.o
cd /builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release/apps/searchjoin && /usr/bin/c++   -DSEARCHJOIN_HUGEDB=TRUE -DSEQAN_APP_VERSION=\"0.5.4\" -DSEQAN_DATE=\"\" -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP=1 -DSEQAN_REVISION=\"tarball\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/builddir/build/BUILD/seqan-seqan-v2.2.0/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -fPIC   -W -Wall -pedantic -fstrict-aliasing -Wstrict-aliasing -fopenmp -DNDEBUG    -DSEQAN_GLOBAL_EXCEPTION_HANDLER=1 -o CMakeFiles/s4_search.dir/search.cpp.o -c /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/searchjoin/search.cpp
{standard input}: Assembler messages:
{standard input}:171632: Error: bad instruction `rep'
{standard input}:171752: Error: bad instruction `rep'
{standard input}:320254: Error: bad instruction `rep'
{standard input}:320606: Error: bad instruction `rep'
apps/searchjoin/CMakeFiles/s4_search.dir/build.make:65: recipe for target 'apps/searchjoin/CMakeFiles/s4_search.dir/search.cpp.o' failed
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/7620/14897620/build.log

**Comment by rrahn** [comment] 2016-07-15 07:54
Can you add this:
```cpp
#elif defined(__arm__)
    asm volatile ("yield" ::: memory);
```
before this line:
https://github.com/seqan/seqan/blob/develop/include/seqan/parallel/parallel_lock.h#L220.

I will be on vacation from now on. So I will  respond to you in two weeks.

**Comment by sagitter** [comment] 2016-07-15 12:12
`bad instruction rep` errors look fixed but `app_test_bs_tools` test is failed.

```
+ ctest --force-new-ctest-process -V
UpdateCTestConfiguration  from :/builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release/DartConfiguration.tcl
UpdateCTestConfiguration  from :/builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release/DartConfiguration.tcl
Test project /builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: app_test_bs_tools
1: Test command: /usr/bin/python2 "/builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/run_tests.py" "/builddir/build/BUILD/seqan-seqan-v2.2.0" "/builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release"
1: Test timeout computed to be: 9.99988e+06
1: Comparing /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/meths_pe_0.bed against /tmp/tmpGrmpwZ/meths_pe_0.bed
1: --- 
1: 
1: +++ 
1: 
1: @@ -7363,7 +7363,7 @@
1: 
1:  21	22239	22240	.	12.3632	+	0
1:  21	22243	22244	.	13.8952	-	0.0695763
1:  21	22244	22245	.	15.2716	+	0
1: -21	22246	22247	.	13.6607	-	0.141157
1: +21	22246	22247	.	13.6605	-	0.141157
1:  21	22253	22254	.	14.5768	+	0
1:  21	22254	22255	.	14.5768	+	0
1:  21	22259	22260	.	15.2812	+	0.0815064
1: DELETING TEMP DIR /tmp/tmpGrmpwZ
1: Executing test for bs_tools
1: =========================
1: 
1: bisar -e3 4 -e4 5 -o /tmp/tmpGrmpwZ/reads_se_N6000_0.CT_GA.verified.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.CT_GA.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.fastq
1: OK
1: bisar -gas -4.5 -ges -2.0 -der 0.001 -bsc 0.99 -gmr 0.5 -i 0.8 -rn 0.001 -pms 0.9 -e3 4 -e4 5 -o /tmp/tmpGrmpwZ/reads_se_N6000_1.CT_GA.verified.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.CT_GA.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.fastq
1: OK
1: bisar -nse -nsi -nsd -gas -4.5 -ges -2.0 -der 0.001 -bsc 0.99 -gmr 0.5 -i 0.8 -rn 0.001 -pms 0.9 -e3 4 -e4 5 -o /tmp/tmpGrmpwZ/reads_se_N6000_2.CT_GA.verified.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.CT_GA.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.fastq
1: OK
1: bisar -nse -nsi -nsd -gas -4.5 -ges -2.0 -der 0.001 -bsc 0.99 -gmr 0.2 -i 0.8 -rn 0.001 -pms 0.9 -e3 4 -e4 5 -o /tmp/tmpGrmpwZ/reads_se_N6000_3.CT_GA.verified.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.CT_GA.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.fastq
1: OK
1: bisar -nse -nsi -nsd -gas -4.5 -ges -2.0 -der 0.001 -bsc 0.99 -gmr 0.8 -i 0.8 -rn 0.001 -pms 0.9 -e3 4 -e4 5 -o /tmp/tmpGrmpwZ/reads_se_N6000_4.CT_GA.verified.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.CT_GA.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000.fastq
1: OK
1: bisar -e3 4 -e4 5 -o /tmp/tmpGrmpwZ/reads_pe_N6000_0.CT_GA.verified.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_pe_N6000.CT_GA.sam /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_pe_N6000.L.fastq /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_pe_N6000.R.fastq
1: OK
1: casbar -nec -mc 6 -msc 5 -mpc 0.5 -hes 0.005 -o /tmp/tmpGrmpwZ/snps_se_0.vcf -b /tmp/tmpGrmpwZ/meths_se_0.bed /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000_2.CT_GA.verified.pos_so.sam
1: OK
1: casbar -nec -mc 2 -msc 3 -mpc 0.5 -hes 0.005 -o /tmp/tmpGrmpwZ/snps_se_1.vcf -b /tmp/tmpGrmpwZ/meths_se_1.bed /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_se_N6000_2.CT_GA.verified.pos_so.sam
1: OK
1: casbar -nec -mc 6 -msc 5 -mpc 0.5 -hes 0.005 -o /tmp/tmpGrmpwZ/snps_pe_0.vcf -b /tmp/tmpGrmpwZ/meths_pe_0.bed /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/hg18_chr21_3000.fa /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/bs_tools/tests/reads_pe_N6000_0.CT_GA.verified.pos_so.sam
1: FAILED
1: ==============================
1:      total tests: 9
1:     failed tests: 1
1: successful tests: 8
1: ==============================
 1/24 Test  #1: app_test_bs_tools ................***Failed   66.58 sec
test 2
```
See full log: https://kojipkgs.fedoraproject.org//work/tasks/5054/14905054/build.log

>I will be on vacation from now on. So I will respond to you in two weeks.

Okay.

**Comment by sagitter** [comment] 2016-07-15 12:15
>I have patched seqan-2.2.0 with rrahn@f48d8a8: failed for missing header file
Build log: https://kojipkgs.fedoraproject.org//work/tasks/6146/14896146/build.log

I obtained the same error on `aarch64 (ARM 64 bit)`. Can you fix it please ?

**Comment by h-2** [comment] 2016-07-15 16:38
This rounding error appears on other platforms combinations, as well, even with x86 (e.g. FreeBSD and Windows). I am thinking about just explicitly activating it for Linux+x86 / Linux+amd64.

**Comment by h-2** [comment] 2016-10-11 10:52
I have a fix for it in #1881, can you see if this makes it work? I don't have any of the effected architectures to test...

**Comment by sagitter** [comment] 2016-10-11 11:57
>I have a fix for it in #1881, can you see if this makes it work? I don't have any of the effected architectures to test...

I'm rebuilding `seqan-2.2.0` by including this patch but i obtain this error with `GCC-6.2.1`:

```
[  0%] Building CXX object apps/alf/CMakeFiles/alf.dir/alf.cpp.o
cd /builddir/build/BUILD/seqan-seqan-v2.2.0/build/Release/apps/alf && /usr/bin/c++   -DSEQAN_APP_VERSION=\"1.1.6\" -DSEQAN_DATE=\"\" -DSEQAN_HAS_EXECINFO=1 -DSEQAN_REVISION=\"tarball\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/builddir/build/BUILD/seqan-seqan-v2.2.0/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fPIC  -W -Wall -pedantic -fstrict-aliasing -Wstrict-aliasing -DNDEBUG    -DSEQAN_GLOBAL_EXCEPTION_HANDLER=1 -o CMakeFiles/alf.dir/alf.cpp.o -c /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/alf/alf.cpp
In file included from /builddir/build/BUILD/seqan-seqan-v2.2.0/include/seqan/basic.h:110:0,
                 from /builddir/build/BUILD/seqan-seqan-v2.2.0/apps/alf/alf.cpp:44:
/builddir/build/BUILD/seqan-seqan-v2.2.0/include/seqan/basic/basic_simd_vector.h:50:27: fatal error: x86intrin.h: No such file or directory
     #include <x86intrin.h>
                           ^
compilation terminated.
```

Full log on Fedora: https://kojipkgs.fedoraproject.org//work/tasks/6760/16046760/build.log

**Comment by h-2** [comment] 2016-10-11 12:15
This should have been fixed by other commits to develop, could you checkout the develop branch and try that instead? [ we just merged the above changes so you just need to checkout develop].

Thank you!

**Comment by sagitter** [comment] 2016-10-11 13:00
https://github.com/seqan/seqan/commit/f1ec3e8f9e91b8c6bb7c02cdaef1fe7577f94a19 is the code of  `seqan-2.2.1` i suppose.

**Comment by sagitter** [comment] 2016-10-12 11:05
Is `aarch64` (64-bit ARM architecture) supported?

```
[ 81%] Building CXX object apps/searchjoin/CMakeFiles/s4_search.dir/search.cpp.o
cd /builddir/build/BUILD/seqan-73a5aaf2aa4cbab14f9354441d9af96f06f2eae7/build/Release/apps/searchjoin && /usr/bin/c++   -DSEARCHJOIN_HUGEDB=TRUE -DSEQAN_APP_VERSION=\"0.5.4\" -DSEQAN_DATE=\"\" -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP=1 -DSEQAN_REVISION=\"tarball\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/builddir/build/BUILD/seqan-73a5aaf2aa4cbab14f9354441d9af96f06f2eae7/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fPIC  -W -Wall -pedantic -fstrict-aliasing -Wstrict-aliasing -fopenmp -DNDEBUG    -DSEQAN_GLOBAL_EXCEPTION_HANDLER=1 -o CMakeFiles/s4_search.dir/search.cpp.o -c /builddir/build/BUILD/seqan-73a5aaf2aa4cbab14f9354441d9af96f06f2eae7/apps/searchjoin/search.cpp
{standard input}: Assembler messages:
{standard input}:176817: Error: unknown mnemonic `rep' -- `rep'
{standard input}:176933: Error: unknown mnemonic `rep' -- `rep'
{standard input}:372403: Error: unknown mnemonic `rep' -- `rep'
{standard input}:372689: Error: unknown mnemonic `rep' -- `rep'
```
Full log:
https://kojipkgs.fedoraproject.org//work/tasks/8387/16058387/build.log

**Comment by rrahn** [comment] 2016-10-12 12:13
Not yet, but working on it. See #1861 for more infos.

**Comment by h-2** [comment] 2016-10-31 21:07
@sagitter can you try if the current develop branch builds fine on Fedora/arm? The debian test matrix looks quite good now, with `pair_align` being disabled and only yara using a little too much memory on some platforms.

**Comment by h-2** [comment] 2016-12-08 16:04
AFAICT this issue should be resolved. Please re-open if you encounter any further issues.

**Closed by h-2** 2016-12-08 16:04 UTC
Labels: feature/-request
