### ISSUE TITLE
global table variables in translation_tables.h causes duplicate symbol linker errors if translation.h is included in more than one file

### ISSUE THREAD

**Issue by vixr** [seqan/seqan#925] opened 2015-04-03 14:57 UTC
If I include translation.h in more than one file in my project, I end up getting linker errors due to the duplicate symbols, presumably because of the global variables defined in the headers. 

~~~~~~~~
duplicate symbol __ZN5seqan29TranslateTableDnaToAminoAcid_INS_11GeneticCodeINS_3TagINS_10Canonical_EEEEEE5VALUEE in:
ref.o
align.o
duplicate symbol __ZN5seqan29TranslateTableDnaToAminoAcid_INS_11GeneticCodeINS_3TagINS_18VertMitochondrial_EEEEEE5VALUEE in:
ref.o
align.o
duplicate symbol __ZN5seqan29TranslateTableDnaToAminoAcid_INS_11GeneticCodeINS_3TagINS_19YeastMitochondrial_EEEEEE5VALUEE in:
ref.o
align.o
...
~~~~~~~~

and so on for the rest of the tables.

Ran into the issue with seqan 1.4.1, but the translation headers seem to be structured in the same way in seqan 2.0.0. I'm compiling with clang in OSX.

**Comment by h-2** [comment] 2015-04-13 11:09
I cannot reproduce this here, I tried with two cpp files that both include all SeqAn modules. Both have functions that call `translate()`, the main function calls both. The program builds and produces correct output.

Can you try SeqAn 2.0 and see if the problem persists, and if yes, provide more details?

Thanks!

**Comment by vixr** [comment] 2015-04-13 19:09
hi h-2 I will look into this. Are there known changes to translation.h / translation_tables.h between 1.4.2 (what I'm using) and 2.0 that might have fixed this? 

So thus far I just looked to see if there was anything obvious in what's changed in 2.0 and I didn't see anything but eventually I am planning to port things over to seqan 2.0.

**Comment by h-2** [comment] 2015-04-14 13:47
> Are there known changes to translation.h / translation_tables.h between 1.4.2 (what I'm using) and 2.0 that might have fixed this?

No, but I still cannot reproduce it, so please update to the new version and then provide more details, if problems persist.

**Comment by h-2** [comment] 2015-04-17 20:56
Since I cannot reproduce it, I will close this issue. If you can reproduce it with 2.0, please reopen it again!

Thanks for you bug report!

**Closed** 2015-04-17 20:56 UTC
Labels: works-for-me
