### ISSUE TITLE
empty sequences in stringset break the FM-index

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1677] opened 2016-04-19 14:40 UTC
Creating an FM-Index over a string set that contains an empty sequence causes undexpected bahaviour on access. 

Take for example the attached genbank file. 
[exophiala_dermatitidis_mitochondrion.gbk.txt](https://github.com/seqan/seqan/files/226103/exophiala_dermatitidis_mitochondrion.gbk.txt)

Due to #1675 the resulting sequence set will contain the original sequence and an empty second sequence (you can verify this). creating the FM-index over these two then seems to work. However merely iterating over the SA-dir will cause something to go into an infinite loop. Removing the second empty sequence restores normal behaviour.

``` c++
#include <iostream>
#include <seqan/index.h>
#include <seqan/seq_io.h>

using namespace seqan;
int main()
{
    StringSet<String<char>, Owner<ConcatDirect<>>> ids;
    StringSet<String<Iupac>, Owner<ConcatDirect<>>> seqs;

    SeqFileIn f("/tmp/test.gbk");
    readRecords(ids, seqs, f);

//     resize(seqs, 1);

    Index<StringSet<String<Iupac>, Owner<ConcatDirect<>>>, FMIndex<> > ix(seqs);
    indexCreate(ix);

    for (auto const & s : indexSA(ix))
        std::cout << s << "\n";
    return 0;
}
```

Note that this might or might not be reproducable in the exact same way. I found it in Lambda and the behaviour depends on a lot of factors (including threading). Also the effect could be "no effect", "crash", "infinite hang"...

**Comment by cpockrandt** [comment] 2016-04-20 08:45
It seems that the compressed SA causes the problem. By using an uncompressed suffix array I could not determine any unexpected behaviour:

    template <typename TSpec = void, typename TLengthSum = size_t>
    struct FMIndexConfig2
    {
        typedef TLengthSum                                  LengthSum;
        typedef WaveletTree<TSpec, WTRDConfig<LengthSum> >  Bwt;
        typedef Levels<TSpec, LevelsRDConfig<LengthSum> >   Sentinels;

        static const unsigned SAMPLING =                    1;
    };

**Comment by h-2** [comment] 2016-04-20 10:01
But if just doing a regular suffix array, not an FM-Index I couldn't reproduce the problem...

**Comment by h-2** [comment] 2016-06-13 10:20
This is an important bug, but the other issues have a higher priority from my POV.

**Comment by cpockrandt** [comment] 2016-10-07 14:59
@h-2 Can you check whether the error still occurs? Last time I checked I couldn't reproduce the error with your input.

**Comment by cpockrandt** [comment] 2016-12-01 15:30
@h-2 Have you tried it yet? If we can't reproduce it, I think we can close this issue.

**Comment by cpockrandt** [comment] 2017-06-19 23:04
@h-2 ping ;)

**Closed** 2017-06-20 12:02 UTC
Labels: bug
