### ISSUE TITLE
problem in LoadReads

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1484] opened 2016-02-22 11:14 UTC
From the mailing list:

> Hi Seqan Devs,
> 
> I am currently working a project that used Seqan 1.4 and now I am updating
> to Seqan 2.1. I think that maybe I have found a bug in Seqan. The problem
> is that LoadReads from FragmentStore is not returning the same as in the
> previous version for the same call, I did a little research  comparing 
> both versions.
> 
> The code of loadReads  have change from one version to the other, in both
> versions it's defined in seqan/store/store_io.h at line 1159 for old
> version and at line 1273 for the new version but the behave is different
> and I think here is the problem.
> 
> in old version there is this part:
> 
> MultiSeqFile multiSeqFileL, multiSeqFileR;
> if (!open(multiSeqFileL.concat, toCString(fileNameL), OPEN_RDONLY))
>   return false;
> if (!open(multiSeqFileR.concat, toCString(fileNameR), OPEN_RDONLY))
>   return false;
> 
> The flow is working correctly and the ifs don't reach the return false but
> in the new version the code is like this
> 
> SeqFileIn seqFileL, seqFileR;
> if (!open(seqFileL, toCString(fileNameL)) || !open(seqFileR,
> toCString(fileNameR)))
>    return false;
> 
> here the execution always always return false. I inspected and its because
>  a different open function its called and here is where I think is the
> bug.
> 
> In seqan 1.4 the open function called is from  string_map defined in
> /include/seqan/file/string_mmap.h however in 2.x the open function that is
> being called is from /include/seqan/stream/formatted_file.h. The open from
> string_mmap.h exists in 2.x and I think is the function that wanted to be
> called. LoadReads calls open with SeqFileIn in the new version while in
> previous with MultiSeqFile but MultiSeqFile is not available in new
> version
> 
> Can you please check if that is a bug
> 
> Thanks in Advance,
> Luis Enrique

**Comment by temehi** [comment] 2016-03-08 19:19
I can not reproduce this bug, anyhow I will try to contact Luis Enrique.

**Comment by xenigmax** [comment] 2016-03-16 17:24
@temehi  Did you contact the person?

**Comment by temehi** [comment] 2016-03-16 18:13
@xenigmax yes, we had a couple of conversation on the mailing list. I asked Luis Enrique to send me his fastq files to locate the problem and I am still waiting.

**Comment by sccluisx** [comment] 2016-03-17 12:46
@temehi Thanks here are the files that were working with previous version of seqan
[seqan_issue_files.zip](https://github.com/seqan/seqan/files/177856/seqan_issue_files.zip)

**Comment by temehi** [comment] 2016-03-17 14:18
@sccluisx on which platform you are using SeqAn? windows?

**Comment by cpockrandt** [comment] 2016-03-17 15:14
Works on Windows with ``VS 14 2015 Win64`` with ``master`` branch.

**Comment by xenigmax** [comment] 2016-03-17 16:23
@temehi @cpockrandt 

> if (!loadReads(fragStore, fileName**R,** fileName**R**)){

Is this correct?

**Comment by temehi** [comment] 2016-03-17 16:43
@xenigmax not really, but it still works with  
```
     if (!loadReads(fragStore, fileNameL, fileNameR)){
```
on OS X and linux. @cpockrandt can please you check again?

**Comment by cpockrandt** [comment] 2016-03-17 16:55
@temehi Still works!

**Comment by temehi** [comment] 2016-03-18 13:17
@xenigmax you may close this issue as we couldn't reproduce the error.

**Closed** 2016-03-18 13:28 UTC

**Comment by sccluisx** [comment] 2017-03-09 12:49
Hi I am retaking this project, now I have isolated the problem and know what is what triggers the bug.
In the zip file I have a very simple code:
`
#include <iostream>
#include <seqan/store.h>
int main(int argc, char * argv[]) {
    seqan::FragmentStore<>  fragStore;
    const char *r1 = argv[1];
    const char *r2 = argv[2];
    auto c1 = loadReads(fragStore, r1, r2);
    std::cout<<"call: "<<std::boolalpha<<c1<<std::endl;
}
`
And it contains seqan1.3 and seqan from the master branch I compile by 
 g++ -g3 -std=c++14  -Iseqan-master/ bug.cpp -o bug   
for master and
 g++ -g3 -std=c++14  -Iseqan-1_3_1/ bug.cpp -o bug

new SEQAN works fine if the input files have extension .fasta however if they have the extension is  *.fastq_N it shows different behaviour as was in the old SEQAN

In this example r1.fasta, r2.fasta and r1.fastq_N, r2.fast1_N are the same file respectively

`
$ g++ -g3 -std=c++14  -Iseqan-old/ bug.cpp -o bug
$ ./bug r1.fasta r2.fasta 
call: true
$ ./bug r1.fastq_N r2.fastq_N 
call: true
$ g++ -g3 -std=c++14  -Iseqan-new/ bug.cpp -o bug
$ ./bug r1.fasta r2.fasta 
call: true
$ ./bug r1.fastq_N r2.fastq_N 
call: false
`
As you can see in seqan 1.3 the reads could be loaded  even if they dont have extension fasta, but in latest seqan the reads are not  loaded
Could you please kindly check this
[seqan_bug.tar.gz](https://github.com/seqan/seqan/files/830850/seqan_bug.tar.gz)
