### ISSUE TITLE
FormattedFile is not move constructible

### ISSUE THREAD

**Issue by JakobSch** [seqan/seqan#2068] opened 2017-05-17 14:46 UTC
Hi,
I am trying to create several .bam files simultaniously and I am failing to create a working `std::vector<seqan::BamFileOut>`.

In the following I show the used seqan version and a working code snippet (although without the functionality I need) as well as several not working snippets.

    $git -C /home/schulzeja/tools/seqan/ log HEAD^..HEAD
    commit d80e19a20e8de488d235cf9d611f5e20eb7fc131
    Merge: 9560e52 0a0faa5
    Author: Hannes Hauswedell <h-2@users.noreply.github.com>
    Date:   Mon Feb 20 13:14:32 2017 +0100
    
        Merge pull request #2040 from h-2/release-prep-2.3.2
    
        Release prep 2.3.2
    
    commit 0a0faa5e51527df4a79f2f527fbd3e2f0c19da90
    Author: Hannes Hauswedell <h2+github.com@fsfe.org>
    Date:   Mon Feb 20 11:57:08 2017 +0100
    
        bump app version numbers for release 2.3.2
    
    commit 1dded79a7bc6ecef0871ece150dea1d939bba136
    Author: Hannes Hauswedell <h2+github.com@fsfe.org>
    Date:   Mon Feb 20 11:56:05 2017 +0100
    
        bump seqan version to 2.3.2

I am compiling with a cmake script ...

    ############################
    ### Header ###
    
    cmake_minimum_required (VERSION 2.8)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -g -pthread -W -Wall -std=gnu++14 -O0")
    include_directories("${PROJECT_BINARY_DIR}")
    
    ############################
    ### setup Zlib and lz4 libraries ###
    
    find_package( ZLIB REQUIRED )
    
    #############################
    ### setup seqan libraries ### needs to be done AFTER searching for Zlib
    
    set (CMAKE_MODULE_PATH "/home/schulzeja/tools/seqan/util/cmake")
    set (SEQAN_INCLUDE_PATH "/home/schulzeja/tools/seqan/include/")
    find_package (SeqAn REQUIRED)
    
    include_directories (${SEQAN_INCLUDE_DIRS})
    add_definitions (${SEQAN_DEFINITIONS})
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${SEQAN_CXX_FLAGS}")
    
    #############################
    ### Build the executables ###
    
    add_executable(seqanIssue issue.cpp )
    target_link_libraries(seqanIssue ${ZLIB_LIBRARIES} ${SEQAN_LIBRARIES})

... and I check the output files with

    $samtools view -H <file.bam>
	$samtools view <file.bam>

	

working script:

	#include <vector>
	#include <seqan/bam_io.h>

	int main() {
	  //// prepare writing of own header. I did not find a better solution

	  // step 1: define header record
	  seqan::BamHeaderRecord headerRecord;
	  headerRecord.type = seqan::BAM_HEADER_FIRST;
	  seqan::resize(headerRecord.tags, 2);
	  headerRecord.tags[0].i1 = "VN";
	  headerRecord.tags[0].i2 = "1.5";
	  headerRecord.tags[1].i1 = "GO";
	  headerRecord.tags[1].i2 = "query";

	  // step 2: define normal record
	  seqan::BamAlignmentRecord alignmentRecord;

	  // step 3: setup empty BamIOContext
	  seqan::StringSet<seqan::CharString> referenceNames;
	  seqan::NameStoreCache<seqan::StringSet<seqan::CharString> > referenceNamesCache(referenceNames);
	  seqan::BamIOContext<seqan::StringSet<seqan::CharString> > bamIOContext(referenceNames, referenceNamesCache);

	  // step 4: fill BamIOContext with actual content
	  seqan::contigNames(bamIOContext) = std::vector<std::string>{"reference1", "reference2"};
	  seqan::contigLengths(bamIOContext) = std::vector<unsigned>{342553423, 568815576};

	  //// create BamFileOut object(s) and write it/them

	  // step 5: create BamFileOut and assign context
	  seqan::CharString filename = "outputFile.bam";
	  seqan::BamFileOut bamFileOut(seqan::toCString(filename));
	  bamFileOut.context = bamIOContext;

	  // step 6: write the header and record
	  seqan::writeHeader(bamFileOut, headerRecord);
	  seqan::writeRecord(bamFileOut, alignmentRecord);
	}
	
not working 1, exchanging step 5 and 6 with ...

	// step 5: create BamFileOut and assign context
	std::vector<seqan::CharString> filenames = {"outputFile1.bam", "outputFile2.bam"};
	std::vector<seqan::BamFileOut> bamFileOuts;
	for (auto e:filenames) {
	seqan::BamFileOut bamFileOut(seqan::toCString(e));
	bamFileOuts.push_back(bamFileOut);
	}

	bamFileOuts[0].context = bamIOContext;

	// step 6: write the header and record
	seqan::writeHeader(bamFileOuts[0], headerRecord);
	seqan::writeRecord(bamFileOuts[0], alignmentRecord);
	
... results in a complicated compiler error.

not working 2, further exchanging `bamFileOuts.push_back(` with `bamFileOuts.emplace_back(` results at runtime in `/home/schulzeja/tools/seqan/include/seqan/bam_io/bam_file.h:280 FAILED!  (BamFileOut: File format not specified.)` and a stack trace.

not working 3, exchanging `bamFileOuts.push_back(` with `bamFileOuts.push_back(std::move(` returns the same error as "not working 2"

not working 4, exchanging step 5 and 6 with ...

	// step 5: create BamFileOut and assign context
	std::vector<seqan::CharString> filenames = {"outputFile1.bam", "outputFile2.bam"};
	std::vector<seqan::BamFileOut*> bamFileOuts;
	for (auto e:filenames) {
	seqan::BamFileOut* bamFileOut = new seqan::BamFileOut(seqan::toCString(e));
	bamFileOuts.push_back(bamFileOut);
	}

	bamFileOuts[0]->context = bamIOContext;

	// step 6: write the header and record
	seqan::writeHeader(*bamFileOuts[0], headerRecord);
	seqan::writeRecord(*bamFileOuts[0], alignmentRecord);
	
... compiles and runs without error but creates two zero byte output files.

Any help is appreciated. I would like to fix that within 7 days, if somehow possible.

**Comment by h-2** [comment] 2017-05-17 17:41
@temehi can you have a look?

**Comment by JakobSch** [comment] 2017-05-22 08:00
Any news?

**Comment by martinjvickers** [comment] 2017-05-22 10:36
@JakobSch I think our problems #2049 are related, just you've got a little further than I have with trying to solve it. I've been trying to write to a BAM/SAM file without copying the context information from an existing BAM/SAM but to no avail. A working example of this would be fantastic if we could get it and update the readthedocs manual with the example.

**Comment by h-2** [comment] 2017-05-22 15:32
The assigned person is currently on vacation and other people in the lab are also quite busy unfortunately :( You can have a look at how our programs do it, maybe that will answer some questions already:
* Yara https://github.com/seqan/seqan/tree/master/apps/yara
* Lambda https://github.com/seqan/lambda/tree/master/src

**Comment by martinjvickers** [comment] 2017-05-22 16:35
@JakobSch I've just noticed on my testing (I'd not noticed this when I first opened my issue) that if you simply change the output file name from a bam file to a sam file (changing nothing else at all) then it works. Obviously it produces a SAM rather than BAM which is not what I want either. When the output file is has a bam file extension it just seg faults. Below is my example;

```
#include <iostream>
#include <seqan/sequence.h>  // CharString, ...
#include <seqan/stream.h>    // to stream a CharString into cout
#include <seqan/file.h>
#include <seqan/arg_parse.h>
#include <seqan/seq_io.h>
#include <seqan/bam_io.h>
using namespace seqan;
using namespace std;

/*
*/
int main(int argc, char const ** argv)
{
	// Initialize BamFile, build header.
	seqan::BamFileOut bamIO(toCString("test_meh.sam"));

	typedef typename BamHeaderRecord::TTag TTag;

	StringSet<CharString> contigNameStore;
	appendValue(contigNameStore, "REFERENCE");
	NameStoreCache<StringSet<CharString> > contigNameStoreCache(contigNameStore);
	BamIOContext<StringSet<CharString> > bamIOContext(contigNameStore, contigNameStoreCache);

	seqan::BamHeader header;
	assignValueById(contigLengths(context(bamIO)), nameToId(contigNamesCache(context(bamIO)), "REFERENCE"), 10000);
	resize(header, 2);
	resize(header[0].tags, 2);
	header[0].type = seqan::BAM_HEADER_FIRST;
	header[0].tags[0].i1 = "VN";
	header[0].tags[0].i2 = "1.3";
	header[0].tags[1].i1 = "SO";
	header[0].tags[1].i2 = "coordinate";
	resize(header[1].tags, 2);
	header[1].type = seqan::BAM_HEADER_REFERENCE;
	header[1].tags[0].i1 = "SN";
	header[1].tags[0].i2 = "REFERENCE";
	header[1].tags[1].i1 = "LN";
	header[1].tags[1].i2 = "10000";
	writeHeader(bamIO, header);

	seqan::BamAlignmentRecord record;

	record.qName = "READ0";
	record.flag = 2;
	record.rID = 0;
	record.beginPos = 0;
	record.mapQ = 8;
	resize(record.cigar, 3);
	record.cigar[0].count = 5;
	record.cigar[0].operation = 'M';
	record.cigar[1].count = 1;
	record.cigar[1].operation = 'I';
	record.cigar[2].count = 4;
	record.cigar[2].operation = 'M';
	record.rNextId = 0;
	record.pNext = 30;
	record.tLen = 40;
	record.seq = "AAAAAAAAAA";
	record.qual = "!!!!!!!!!!";
	writeRecord(bamIO, record);

	record.qName = "READ0";
	record.flag = 3;
	record.rID = 0;
	record.beginPos = 2;
	record.mapQ = 8;
	resize(record.cigar, 3);
	record.cigar[0].count = 5;
	record.cigar[0].operation = 'M';
	record.cigar[1].count = 1;
	record.cigar[1].operation = 'I';
	record.cigar[2].count = 4;
	record.cigar[2].operation = 'M';
	record.rNextId = seqan::BamAlignmentRecord::INVALID_REFID;
	record.pNext = seqan::BamAlignmentRecord::INVALID_POS;
	record.tLen = seqan::BamAlignmentRecord::INVALID_LEN;
	record.seq = "AAAAAAAAAA";
	record.qual = "!!!!!!!!!!";
	writeRecord(bamIO, record);
	
	close(bamIO);

	return 0;
}
```

**Comment by JakobSch** [comment] 2017-05-23 10:02
@h-2 Thank you for the hints but after a quick glance at the command line parser of yara and lambda, both seem to write only one output file (which I can also do at the moment).
However I might have missed something.

**Comment by martinjvickers** [comment] 2017-05-23 10:11
@h-2 Is it possible that there is an actual bug here? In my example above I can create a SAM but if I rename the output file with a bam extension I get a segfault. Have I made a mistake here or should this work? 

To clarify I just tried this on 2.2.0 as well as the most recent master branch.

**Comment by martinjvickers** [comment] 2017-05-24 12:36
@JakobSch You suggested (in another Issue) to take a look at the CMakeList.txt file to see if zlib was working correctly. And it wasn't. The issue I had was that I had called --static after the find_package step (I now noticed that there is some information about this in the docs https://seqan.readthedocs.io/en/master/Infrastructure/Use/FindSeqAnCMake.html#static-builds).

A working version of the above is here;

https://gist.github.com/martinjvickers/231c21d1ceb9e94c602e47346ddcfdca

Thanks for nudging me in that direction @JakobSch

**Comment by temehi** [comment] 2017-06-07 08:24
Hi, I think the problem is due to `seqan::BamFileOut` not being  **copy-assignable**. [`std::vector<T>` requeres the type T to be **copy-assignable**1](http://en.cppreference.com/w/cpp/container/vector) and `seqan::BamFileOut` is not. 


you can check this using:
```
std::cout << "Is seqan::BamFileOut copy-assignable? "
          << std::is_copy_assignable<seqan::BamFileOut>::value << '\n';
```

**Comment by JakobSch** [comment] 2017-06-16 11:14
Hi, thank you for the answer.
This explains "not working 1" but not the others. At least as far as I have understood c++ (which is not really far).
Shouldn't ```bamFileOuts.emplace_back(``` and ```bamFileOuts.push_back(std::move(``` still work as it does not copy the object?

At least creating the objects on the heap as done in "not working 4" should neither require copying or moving of the objects.

**Comment by tloka** [comment] 2017-12-01 10:16
Hey,
I work on the same project as @JakobSch has done.
The problem with vectors is that BamFileOut is also not move-assignable. This is required for vectors since they are always stored sequentially in the memory. Thus, if the reserved memory is full the complete vector must be moved which doesn't work with objects as BamFileOut that are not move-assignable.
Thus, I got it running by using std::deque instead. std::deque can use different locations in memory and therefore doesn't require move- or copy-assignability. To fill the vector, use emplace_back to perform in-place initialization. However, access time can be a bit slower than with vectors. Alternatively you could create pointers to your BamFileOut objects and fill a vector with these pointers (also tried that and it worked).

**Comment by JakobSch** [comment] 2017-12-01 10:50
Hey thanks a lot for your answer. At least there exists a working version now.
However, the missing move-assignability explains example 2 and 3 but still not example 4. There I construct the BamFileOut objects on the heap (which should be very similar to what the deque does).

Wait, in your last sentence you claim that you got it running with pointers. Isn't that exactly what I did in example 4?

**Comment by tloka** [comment] 2017-12-01 12:05
@JakobSch Without having it tried, the problem in example 4 seems to be something different.
I expect that the problem there is that you create the BFO objects inside the scope of the for loop, so I would expect it to be destructed before something is written to it (since you even set context and write the header behind the scope). So you initialize the BFO (at this point, the 0-byte file is created on your system), put a pointer to it to the vector, BFO is destructed at the end of scope and you set context and write header and record via the pointer pointing to the destructed object.
Only thing I don't really understand in that case is why this does not lead to an exception.

**Comment by JakobSch** [comment] 2017-12-01 12:08
Technically, the `new` should prevent the destruction.

**Comment by tloka** [comment] 2017-12-01 12:17
@JakobSch Sure you are right, didn't realize that. 
Using pointers is actually the solution that is pretty often recommended in blogs for filestreams in general. And I remember having it running with pointers like half a year ago or so, thus I am pretty sure it should work in general. If this is of high importance, I can have another more detailed look at the pointers (but this may take a while).

**Comment by temehi** [comment] 2017-12-20 10:50
@JakobSch 
I think the reason example 4 is producing 0-byte files is that the bam files were left open.
adding the following should fix your issue. Please let me know if this solves the issue.

```
    for (auto bf:bamFileOuts)
    {
        close(*bf);
    }
```

**Comment by h-2** [comment] 2018-01-08 12:37
What is the status here?

**Comment by tloka** [comment] 2018-01-08 12:56
I currently don't really have time to check again, but I think the missing close could actually be the reason why example 4 was not working. I remember that I had a similar behavior (producing 0-byte files) some months ago that I finally fixed by manually closing the BAM files.
However, I think that this issue can be closed since at least one working solution exists (using std::deque). Actually, using this, I even managed to write from different threads to several BAM files simultaneously. You could check it again with the pointer version, but I am pretty sure this should work as well.

**Comment by h-2** [comment] 2018-01-24 10:21
I have tried making `FormattedFile` move constructible, but it wasn't feasible in the current codebase. Moving this to SeqAn3.

**Comment by h-2** [comment] 2018-11-19 17:12
SeqAn3 files are move-constructible.

**Closed by h-2** 2018-11-19 17:12 UTC
