### ISSUE TITLE
Warnings on Visual Studio builds

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1084] opened 2015-08-12 12:03 UTC
When doing cmake type debug, somehow all the demos have -W3 instead of -W2, I dont know why this happens, but it causes a lot of warnings to pop up.
Thats probably also the reason why the nightly builds have so many warnings on vc.

**Comment by catkira** [comment] 2015-08-12 12:37
See this commit: https://github.com/catkira/seqan/commit/facc4871a65719a7fb9959c79dbbecd3813e3836

**Comment by catkira** [comment] 2015-08-12 13:08
https://github.com/catkira/seqan/commit/87f021c60960763da362d2239f63d3a56274abc9

After this commit, all the warnings are gone (somehow)

**Comment by catkira** [comment] 2015-08-12 13:29
http://www.cmake.org/cmake/help/v3.0/command/add_subdirectory.html
"The CMakeLists.txt file in the specified source directory will be processed immediately by CMake before processing in the current input file continues beyond this command."
So I variables have to be set before you do add_subdirectory.

**Comment by rrahn** [comment] 2015-08-13 14:34
@catkira Can you please add a PR for catkira@facc487 to master and develop. 
In general I think we should use W3 as the standard warning level as it seems to fit more the -Wall of gcc. Anyway, since we are not going to fix all the warnings that will pop up then, we defer this to the 2.1.0 release.
Just one question, why is this catkira@87f021c necessary?

**Comment by catkira** [comment] 2015-08-13 17:55
@rrahn I dont know why its neccessary, I just figured it out by trial and error. For -W3, yes I agree, it would be better to switch to W3 or W4 for vc builds in the long run. For now, my cmake fixes clear all errors on W2 level.

**Comment by rrahn** [comment] 2016-01-27 23:52
Ok the parallel_queue_example error: fatal error C1001: An internal error has occurred in the compiler.
seems to be a known bug: https://social.msdn.microsoft.com/Forums/vstudio/en-US/62365d65-c1e0-404f-a2c3-bded754d7ae5/regression-in-visual-studio-2015-update-1?forum=vcgeneral
So I will disable this demo for now until the problem is fixed upstream.
@h-2 Maybe you can ask the constexpr guy if he knows something about it?

**Comment by rrahn** [comment] 2016-01-28 09:47
OK once #1381 has passed and #1372 is fixed I think we are good on windows.

**Comment by h-2** [comment] 2016-02-10 21:10
@rrahn @catkira is there anything legt to do Herr vor can it be closed?

**Comment by h-2** [comment] 2016-02-11 15:15
@rrahn there are still errors on windows pertaining to the random module, can you have a look?

**Comment by h-2** [comment] 2016-02-12 17:43
fixed by #1150 #1453 #1429

**Closed by h-2** 2016-02-12 17:43 UTC
Labels: compiler-warning

**Comment by catkira** [comment] 2016-02-14 23:14
Hi, i can not say this now, because I have switched with seqan to linux :smile_cat:
