### ISSUE TITLE
Support bcf

### ISSUE THREAD

**Issue by xenigmax** [seqan/seqan#1931] opened 2016-11-09 21:41 UTC
BCF is a binary version of vcf.
Many tools support this format as an output instead of vcf.

https://samtools.github.io/bcftools/bcftools.html

**Comment by xenigmax** [comment] 2016-11-09 23:33
https://github.com/samtools/hts-specs

**Comment by h-2** [comment] 2016-11-10 12:00
this is a duplicate of #1652

**Closed by h-2** 2016-11-10 12:00 UTC
Labels: feature/-request
