### ISSUE TITLE
/seqan/include/seqan/stream/zipstream/zutil.h:212:37: error: expected initializer before ‘OF’

### ISSUE THREAD

**Issue by mmokrejs** [seqan/seqan#899] opened 2015-03-05 20:54 UTC
In https://github.com/seqan/seqan/issues/772#issuecomment-77446340 I fetched seqan sources. after the commands shown there I did "make". Compiling it using gcc-4.8.3 gives me:

<pre>
...
Scanning dependencies of target test_stream
[  7%] Building CXX object tests/stream/CMakeFiles/test_stream.dir/test_stream.cpp.o
In file included from /mnt/external/tmp/seqan/include/seqan/stream/stream_compressor.h:42:0,
                 from /mnt/external/tmp/seqan/include/seqan/stream.h:89,
                 from /mnt/external/tmp/seqan/tests/stream/test_stream.cpp:39:
/mnt/external/tmp/seqan/include/seqan/stream/zipstream/zutil.h:212:37: error: expected initializer before ‘OF’
 typedef uLong (ZEXPORT *check_func) OF((uLong check, const Bytef *buf,
                                     ^
/mnt/external/tmp/seqan/include/seqan/stream/zipstream/zutil.h:214:16: error: expected initializer before ‘OF’
 voidpf zcalloc OF((voidpf opaque, unsigned items, unsigned size));
                ^
/mnt/external/tmp/seqan/include/seqan/stream/zipstream/zutil.h:215:16: error: expected initializer before ‘OF’
 void   zcfree  OF((voidpf opaque, voidpf ptr));
                ^
In file included from /mnt/external/tmp/seqan/include/seqan/basic.h:61:0,
                 from /mnt/external/tmp/seqan/tests/stream/test_stream.cpp:38:
/mnt/external/tmp/seqan/include/seqan/basic/basic_exception.h:358:37: warning: ‘seqan::_globalExceptionHandler’ defined but not used [-Wunused-variable]
 static const std::terminate_handler _globalExceptionHandler = std::set_terminate(globalExceptionHandler);
                                     ^
tests/stream/CMakeFiles/test_stream.dir/build.make:54: recipe for target 'tests/stream/CMakeFiles/test_stream.dir/test_stream.cpp.o' failed
make[2]: *** [tests/stream/CMakeFiles/test_stream.dir/test_stream.cpp.o] Error 1
CMakeFiles/Makefile2:1820: recipe for target 'tests/stream/CMakeFiles/test_stream.dir/all' failed
make[1]: *** [tests/stream/CMakeFiles/test_stream.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by temehi** [comment] 2015-04-13 10:44
@mmokrejs  Do you still have this problem or is it solved with #772?

**Comment by mmokrejs** [comment] 2015-04-14 10:04
I do not have this problem with seqan-2.0.0 with a patch from
https://www.mail-archive.com/gentoo-commits@lists.gentoo.org/msg99608.html

**Comment by temehi** [comment] 2015-04-14 10:48
Thanks @mmokrejs ! @esiragusa you can close the issue now.

**Comment by h-2** [comment] 2015-04-14 11:15
wait, maybe we should incorporate the patch instead of relying on downstream?

**Comment by esiragusa** [comment] 2015-04-14 11:35
@h-2 yes! @temehi would you please prepare a PR?

**Comment by temehi** [comment] 2015-04-15 10:45
I don't think the patch is the way to go. The problem is not with "/include/seqan/stream/zipstream/zutil.h".
initialization of "OF" should be done in the <zlib.h> not in SeqAn.

**Comment by h-2** [comment] 2015-04-15 12:30
Hm, but apparently not all zip libraries provide this. If we add this to our zutil, it shouldn't hurt anyone, right?
```c++
#ifndef OF
#define OF(x) x
#endif
```

**Comment by esiragusa** [comment] 2015-04-15 12:44
Really? If so, then let's do as @h-2 proposed.

**Comment by h-2** [comment] 2015-04-16 09:31
@mmokrejs can you confirm the patch by @temehi fixes your build problems?

**Comment by mmokrejs** [comment] 2015-04-16 10:39
> [FIXED #899] of macro defined under zutil.h

This one ( b8e66974dc39a802197e56a7db24d282a6ed2fc5 ) works for me as well. I am not a C programmer but couldn't configure check for a zlib version and adjust properly? Yeah, no configure used ... ;-) Sounds hackish but I don't care. It also works. Thanks. I have zlib-1.2.8, btw.

**Comment by h-2** [comment] 2015-04-16 10:47
Well, if this works, we will take it I think ;)

**Closed by h-2** 2015-04-16 10:47 UTC
Labels: bug
