### ISSUE TITLE
softcode fasta file extension in Mason

### ISSUE THREAD

**Issue by tseemann** [seqan/seqan#1670] opened 2016-04-17 05:51 UTC
It appears the apps only support `.fa` and `.fasta`.

NCBI has a pseudo-standard of 
- `.fna` for genomic contigs
- `.faa` for protein sequences
- `.frn` for nucleotide RNA features
- `.ffn` for nuceotide DNA features (or just CDS)

**Comment by h-2** [comment] 2016-04-18 09:56
Thanks for the feedback!

As you can see here:
https://github.com/seqan/seqan/blob/master/include/seqan/seq_io/fasta_fastq.h#L109
all of the extensions are actually supported.

But maybe some apps hard-code the extensions to be only a subset... which apps were your referring to?

**Comment by h-2** [comment] 2016-04-20 09:43
Are you reffering to Mason? I see that it hardcodes the extensions:
https://github.com/seqan/seqan/blob/master/apps/mason2/mason_genome.cpp#L118
It should instead be "softcoded", as described in #838

**Comment by h-2** [comment] 2016-04-20 09:47
I am marking this as a duplicate of #838

**Comment by tseemann** [comment] 2016-04-20 21:30
Yes I did mean `mason`  thanks for digging into the problem!

**Comment by Funatiq** [comment] 2017-08-30 15:11
The problem still consists in the mason apps. There were some suggestions in #838 to fix this, but it got closed without resolving this issue here.

**Comment by h-2** [comment] 2017-09-01 10:26
Renaming and re-opening. 

The abovementioned line in mason needs to be changed from
```diff
-setValidValues(parser, "out-file", "fa fasta");
+setValidValues(parser, "out-file", toCString(concat(getFileExtensions(SeqFileOut()), ' ')));
```
This is now tagged for milestone 2.4.0, but if  you could make a PR for this it would certainly be fixed faster 😃

**Comment by Funatiq** [comment] 2017-09-01 11:20
Well I'm a little confused about how you handle those things. I've seen something like
`setValidValues(parser, "seq", getFileExtensions(Fasta()));`
or 
`setValidValues(parser, "o", SeqFileOut::getFileExtensions());`
in the other apps. There are many apps like mason that still have hardcoded file extensions for parsing.
Is there a difference between those code lines?

**Comment by h-2** [comment] 2017-09-01 13:07
Yes, there is. The SeqFileOut's getFileExtensions also add extensions based on supported compression formats, e.g. `.faa.gz`. The line I posted above is how other apps like Lambda do it so I am sure that will work.

**Comment by rrahn** [comment] 2017-09-18 09:42
is this issue resolved?

**Closed** 2017-12-19 11:42 UTC
Labels: app, duplicate
