### ISSUE TITLE
Python scripts incompatible with Python 3

### ISSUE THREAD

**Issue by karel-brinda** [seqan/seqan#1482] opened 2016-02-19 20:46 UTC
Python scripts seem not to be compatible with Python 3. On some computers, `#!/usr/bin/env python` returns Python 3. It happens, e.g., with Anaconda which sometimes prepends its directory to `PATH`.

``` shell
Scanning dependencies of target dox
Traceback (most recent call last):
  File "/home/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/../util/bin/dox.py", line 14, in <module>
    sys.exit(main())
  File "/home/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/../util/bin/dox.py", line 10, in main
    import seqan.dox.pure
  File "/home/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/util/py_lib/seqan/dox/pure.py", line 129
    print 'Scanning %s...' % path
                         ^
SyntaxError: Missing parentheses in call to 'print'
dox/CMakeFiles/dox.dir/build.make:57: recipe for target 'dox/CMakeFiles/dox' failed
make[5]: *** [dox/CMakeFiles/dox] Error 1
CMakeFiles/Makefile2:167: recipe for target 'dox/CMakeFiles/dox.dir/all' failed
make[4]: *** [dox/CMakeFiles/dox.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/seqan.dir/build.make:110: recipe for target 'cmake-ext/seqan-prefix/src/seqan-stamp/seqan-build' failed
make[2]: *** [cmake-ext/seqan-prefix/src/seqan-stamp/seqan-build] Error 2
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/seqan.dir/all' failed
make[1]: *** [CMakeFiles/seqan.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by h-2** [comment] 2016-02-22 10:41
@cpockrandt Do you know python? Can you look into this?

**Comment by cpockrandt** [comment] 2016-02-24 13:51
Hi @karel-brinda 

Thanks for your feedback. I changed it to ``#!/usr/bin/env python`` to have the same shebangs throughout our library. Could you check whether that solves your problem (you can check it out here: https://github.com/cpockrandt/seqan/tree/fix/python-shebangs)? I couldn't reproduce the problem on my system.

**Comment by cpockrandt** [comment] 2016-02-25 10:59
Hi @karel-brinda 

We updated our python scripts to ensure that python2 is called. Thanks again for your help!

**Comment by karel-brinda** [comment] 2016-02-25 13:15
Hello @cpockrandt, @h-2 and @marehr,

I am afraid that this will require more testing. 

## Testing 

Here is a set of commands to verify what ``/usr/bin/env`` returns.

```
/usr/bin/env python -V
/usr/bin/env python2 -V
/usr/bin/env python2.6 -V
/usr/bin/env python2.7 -V
/usr/bin/env python3 -V
```

## Results on machines I use

I did some modifications in my files (``.bashrc``, etc.) after I had reported the bug (to be able to compile Seqan) so ``$ /usr/bin/env python`` already returns Python 2.7.


**Machine 1** (laptop, OSX) - no python2 (!!)
```
$ /usr/bin/env python -V
Python 2.7.10
$ /usr/bin/env python2 -V
env: python2: No such file or directory
$ /usr/bin/env python2.6 -V
Python 2.6.9
$ /usr/bin/env python2.7 -V
Python 2.7.10
$ /usr/bin/env python3 -V
Python 3.4.3
```

**Machine 2** (desktop, Linux OpenSuSE)
```
$ /usr/bin/env python -V
Python 2.7.9
$ /usr/bin/env python2 -V
Python 2.7.9
$ /usr/bin/env python2.6 -V
/usr/bin/env: python2.6: No such file or directory
$ /usr/bin/env python2.7 -V
Python 2.7.9
$ /usr/bin/env python3 -V
Python 3.4.1
```

**Machine 3** (server, some Linux)
```
$ /usr/bin/env python -V
Python 2.7.9
$ /usr/bin/env python2 -V
Python 2.7.9
$ /usr/bin/env python2.6 -V
/usr/bin/env: python2.6: No such file or directory
$ /usr/bin/env python2.7 -V
Python 2.7.9
$ /usr/bin/env python3 -V
Python 3.4.3
```

**Machine 4** (server, some Linux)
```
$ /usr/bin/env python -V
Python 2.7.11
$ /usr/bin/env python2 -V
Python 2.7.11
$ /usr/bin/env python2.6 -V
/usr/bin/env: python2.6: No such file or directory
$ /usr/bin/env python2.7 -V
Python 2.7.11
$ /usr/bin/env python3 -V
Python 3.4.3
```

**Machine 5** (server, some Linux)
```
$ /usr/bin/env python -V
Python 2.7.5
$ /usr/bin/env python2 -V
Python 2.7.5
$ /usr/bin/env python2.6 -V
Python 2.6.6
$ /usr/bin/env python2.7 -V
Python 2.7.5
$ /usr/bin/env python3 -V
Python 3.1.3
```

## Possible solutions

### Make Seqan scripts for Python 2.7 but compatible with Python 3

Use
```python
#! /usr/bin/env python

from __future__ import print_function
```

Possible problems: on machines with extra old Python. However, since you require GCC 4.9+ (released in 2014), insisting on support for Python 2.6- (released in 2008) would be strange.

### Detect path for Python 2 with CMake

and run a script which updates the ``#!`` lines. I cannot estimate how easy/complicated it is.

### Create a Python loader

which executes
```bash
/usr/bin/env python2 || /usr/bin/env python2.7 || /usr/bin/env python2.6 || /usr/bin/env python
```

**Comment by karel-brinda** [comment] 2016-02-29 12:46
So I returned back to my original configuration setting on my OSX laptop and now I am getting the following results:
```
$ python -V
Python 3.5.1 :: Anaconda 2.4.1 (x86_64)
$ /usr/bin/env python -V
Python 2.7.10
$ /usr/bin/env python2 -V
env: python2: No such file or directory
$ /usr/bin/env python2.6 -V
Python 2.6.9
$ /usr/bin/env python2.7 -V
Python 2.7.10
$ /usr/bin/env python3 -V
Python 3.4.3
```
To sum up, there is no ``python2`` and ``/usr/bin/env python`` returns Python 3. I think that I am not alone with such environment.

**Comment by karel-brinda** [comment] 2016-02-29 14:46
Hello @cpockrandt, @h-2 and @marehr,

I think I have found the main problem. Seqan relies on CMake ``find_package (PythonInterp)
`` and does not check versions, see https://github.com/seqan/seqan/blob/3056fcaa07d902679c72fe6c149bcddccdf53ef8/dox/CMakeLists.txt#L12. So in my case, it finds Python 3 and tries to execute Pythons script with it:
```
On-y-go:dox karel$ make VERBOSE=1 2>&1 | tail -n 13
cd /Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan-build/dox && /Users/karel/anaconda3/bin/python /Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/../util/bin/dox.py -b /Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/.. -i /Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/../include/seqan -i /Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/pages --image-dir /Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/images
Traceback (most recent call last):
  File "/Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/../util/bin/dox.py", line 14, in <module>
    sys.exit(main())
  File "/Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/dox/../util/bin/dox.py", line 10, in main
    import seqan.dox.pure
  File "/Users/karel/github/cmake-ext/tests/cmake-ext/seqan-prefix/src/seqan/util/py_lib/seqan/dox/pure.py", line 129
    print 'Scanning %s...' % path
                         ^
SyntaxError: Missing parentheses in call to 'print'
make[2]: *** [dox/CMakeFiles/dox] Error 1
make[1]: *** [dox/CMakeFiles/dox.dir/all] Error 2
make: *** [all] Error 2
```

This should help: https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html
> The Python_ADDITIONAL_VERSIONS variable can be used to specify a list of version numbers that should be taken into account when searching for Python. You need to set this variable before calling find_package(PythonInterp).

Btw. is it possible to skip the Dox step when building Seqan with ``-DSEQAN_BUILD_SYSTEM=SEQAN_RELEASE_LIBRARY``? Something like ``-DNO_DOX=1`` would be very useful: some compilation time would be saved and Python related problems would not appear.

**Comment by h-2** [comment] 2016-02-29 16:54
@karel-brinda you are right about this. Seeing that making the scripts python3 compatible is the future-proof way to go and would solve all the issues, I think we should focus on that.
@cpockrandt and @smehringer can you communicate on this? Thanks!

**Comment by h-2** [comment] 2016-02-29 17:04
> Btw. is it possible to skip the Dox step when building Seqan with -DSEQAN_BUILD_SYSTEM=SEQAN_RELEASE_LIBRARY? Something like -DNO_DOX=1 would be very useful: some compilation time would be saved and Python related problems would not appear.

Please be aware that SEQAN_LIBRARY_RELEASE is not intended for end users or downstream packagers. **We** use this to create extra source packages for you that include only header and dox (but not the mechanism for creating the dox):
http://packages.seqan.de/ [first links / "SeqAn Library"]
Use these if you want a light-weight install that has no build step (and thus no build dependencies).

**Comment by karel-brinda** [comment] 2016-02-29 17:22
@h-2 I usually add Seqan to my projects using CMake External Project mechanism, see https://github.com/karel-brinda/cmake-ext/blob/master/seqan.cmake. I can replace there the git repository by url of the package from Platform Independent Download and just change ``include_directories`` (is this the intended way of usage?). However, I normally prefer Github repositories to project specific websites (it is more reliable in a long-time perspective -- urls of Seqan downloads might be changed after some time).

**Comment by h-2** [comment] 2016-02-29 17:31
> I usually add Seqan to my projects using CMake External Project mechanism

Ah, I was unfamiliar with that. But if indeed you are only using the headers and nothing else, can you not overwrite the install step with  `cp -a SOURCE TARGET`?

It is not a lot of work though, maybe we can add a flag...

**Comment by h-2** [comment] 2016-02-29 18:16
btw. this also blocks #1398 because on OpenBSD there are neither symlinks to python2 nor to python (only the full versions).

**Comment by xenigmax** [comment] 2016-03-18 13:41
@cpockrandt @h-2 
Here are my suggestions about this.

1)
If the problem is just about "print," I think we can simply replace python2.x style to 3.x style.
Since 2.x supports 3.x style as well. (which is odd but..)

2)
Or why don't we just let others know that there is a transformer?
https://docs.python.org/2/library/2to3.html

**Comment by cpockrandt** [comment] 2016-03-18 13:43
@smehringer was working on this issue. Afaik there are more problems than just "print". She also tried the 2to3 transformer out but it resulted in major code changes and didn't even work afterwards.

**Comment by smehringer** [comment] 2016-03-18 13:49
That's right. It resulted in code changes in about 1400 lines and still did not run without errors (which might be due to the automatic 2to3 transformer but anyway). In addition a lot of changes will not be compatible with pyhon2 (e.g. syntax and library name changes).

**Comment by xenigmax** [comment] 2016-03-18 13:55
> That's right. It resulted in code changes in about 1400 lines and still did not run without errors (which might be due to the automatic 2to3 transformer but anyway). In addition a lot of changes will not be compatible with pyhon2 (e.g. syntax and library name changes).

Then, it should be a huge job. I have tried dox a while.. and I can sense that it's not a simple task.
I think we have to make a decision now.

@h-2, what do you think about below?
1) Notice clearly that the current SeqAn dox only supports python 2.x 
2) Postpone this issue to a major release.

**Comment by h-2** [comment] 2016-06-13 10:13
I am moving this to 2.3 for lack of time, but since it is a bigger issue, please look at it soon after the 2.2 release.

**Comment by h-2** [comment] 2016-10-05 09:24
Even if we are working on SeqAn3, SeqAn2 will be used for a long time and we need to come up with something here that works also in the future.
@xenigmax and @smehringer how much time would it take to port the scripts to a dialect that works on python2 and python3? Since we want to get rid of the dddoc dependency[ #1820 ]  , someone needs to look into the scripts anyway...

> Something like -DNO_DOX=1 would be very useful
@karel-brinda we have `SEQAN_NO_DOX` that you can set...

**Comment by smehringer** [comment] 2016-10-06 07:05
@h-2 I don't think there is chance of writing a python script in a dialect that supports both python2 and python3 since I remember major syntax and namespace changes. Maybe we can have one script for each version and auto-detect which one is needed?

**Comment by marehr** [comment] 2016-10-07 07:23
> btw. this also blocks #1398 because on OpenBSD there are neither symlinks to python2 nor to python (only the full versions).

@h-2 There is a pep http://legacy.python.org/dev/peps/pep-0394/ that suggest that python2 and python3 should exist. Can you tell my, why BSD's don't follow that? 

> This PEP provides a convention to ensure that Python scripts can continue to be portable across *nix systems, regardless of the default version of the Python interpreter (i.e. the version invoked by the python command).
-    `python2` will refer to some version of Python 2.x.
-    `python3` will refer to some version of Python 3.x.
-    for the time being, all distributions should ensure that `python` refers to the same target as `python2`.
-    however, end users _should_ be aware that `python` refers to `python3` on at least Arch Linux (that change is what prompted the creation of this PEP), so `python` should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3.
-    **in preparation for an eventual change in the default version of Python, Python 2 only scripts should either be updated to be source compatible with Python 3 or else to use `python2` in the shebang line.**

**Comment by h-2** [comment] 2016-10-07 09:00
> @h-2 There is a pep http://legacy.python.org/dev/peps/pep-0394/ that suggest that python2 and python3 should be available. 

Interesting.

> Can you tell my, why BSD's don't follow that? 

FreeBSD follows it. MacOS and OpenBSD apparently don't. I will ask the OpenBSD-people.

I still propse that we 
1) adapt the cmake script to detect python2 properly
2) adapt the shell script to call  {python2|python2.7|python2.6} **explicitly**
3) we *can* change the shebang to python2, as well, seeing that step 1 and 2 should work on MacOS and OpenBSD, too.

**Comment by xenigmax** [comment] 2016-11-02 19:36
I just made a pull request about this.

> 1) adapt the cmake script to detect python2 properly

Now CMake can find 2.x .
Please check my pull request about this.

> 2) adapt the shell script to call {python2|python2.7|python2.6} explicitly
> 3) we can change the shebang to python2, as well, seeing that step 1 and 2 should work on MacOS and OpenBSD, too.

I would like to make sure about this.

Currently, all the python executables in /util/bin/ use  *#!/usr/bin/env python2.*.
And this is the standard way according to PEP.

So there are two ways...

1) Let MacOS/OpenBSD users know we need python2 that is linked to python2.x for **building dox**.
I can simply add some bash code for checking "python2" to .sh files and let them know the situation.
A user has to 
a. make a symbolic link(which is the standard) if he/she really wish to build dox.
b. simply *does not care about building dox* and use seqan for their job.

b was impossible since it gives error messages in test steps. 
(Now it's possible by my pull request..)

2) Change .sh files accordingly in CMake step.
I can add some CMake code for changing all .sh files that call .py.

I'm asking this since it's about the policy. 
The difference of my efforts between 1) and 2) are neglectable.
However, If we handle the situation(some OS does not follow the official guideline, and the function is not related to the core of seqan) like 2), we may apply the same principle in other cases.

So what is your decision?
I will update my PR accordingly.

**Comment by h-2** [comment] 2016-12-08 18:40
@xenigmax  Is this issue done?

**Comment by rrahn** [comment] 2016-12-12 09:33
@xenigmax ping

**Comment by xenigmax** [comment] 2016-12-12 17:14
@h-2 @rrahn  Please check my another PR #1969

**Closed** 2016-12-13 11:24 UTC
Labels: bug
