### ISSUE TITLE
Remove `seqan.dddoc` and deprecated stuff under util/py_lib

### ISSUE THREAD

**Issue by kdmurray91** [seqan/seqan#1820] opened 2016-07-22 13:06 UTC
Hi,

I'm packaging Seqan 2.x for the Debian and derivative operating systems. So far, so good, however it appears that there are many minified javascript and even Flash programs within the documentation helper code (specifically under [dddoc/tpl](https://github.com/seqan/seqan/tree/master/util/py_lib/seqan/dddoc/tpl)). These are not allowed (even in sources) within debian, as they are in essence not source code but compiled output.

My question is: are these used for anything user-facing? I notice the `dddoc` module has not been modified in some time, and there is a second `dox` helper. Is there any harm in excluding this module from the debian packages? Will the user-facing documentation still build?

Thanks,
Kevin (On behalf of [Debian Med](https://wiki.debian.org/DebianMed))

**Comment by h-2** [comment] 2016-07-22 16:45
Hi Kevin,

thanks for working on porting SeqAn2 first of all. As I mentioned previously to @mr-c of Debian Med in #1478 we do recommend strongly against using a full checkout of the repository for building the library packages. Having a huge meta-repository with all sorts of utils and apps is a legacy that we really rather not pass on to downstream.
Precisely for this purpose we offer "library source packages" on http://packages.seqan.de
These contain only the source of the library and corresponding html documentation and no python code or applications, they also have no build step and no external dependencies. Please see also our recommendations for downstream packaging here: http://seqan.readthedocs.io/en/master/Infrastructure/Manage/Releases.html#downstream-packaging

If you insist on building from the full repository checkout, you can remove all the dddoc stuff, as it is all legacy code, however, the dox stuff is required for generating the API documentation and some unit tests might use python, as well, I am not sure right now.

In any case we would be extremely happy to see a more recent version come to Debian and derivates.

Regards,
Hannes

**Comment by rrahn** [comment] 2016-07-25 10:56
@kdmurray91 @h-2 I think the dox still has some dependencies to the dddoc. So removing the subdirectory may cause some issues. But I am not so sure. It was some time ago I looked into it.

**Comment by h-2** [comment] 2016-09-07 09:58
@xenigmax since you have worked with the dox system recently I am reassigning this to you, I hope thats ok!

**Comment by xenigmax** [comment] 2016-09-16 10:44
I can't predict exact consequences after removing that parts, but I would say @rrahn is correct about this.
You will encounter problems on building docs which we can't cope with immediatly. 
I would like to recommand you to follow @h-2 's suggestion about this.

**Comment by h-2** [comment] 2016-09-18 14:09
@xenigmax @rrahn I still think that removing legacy code from the repository is a worthwhile effort especially binary stuff like flash (why is that even there!?). If this helps getting an up to date version of seqan into Debian it is all the more important.
Could you have a look at what specifically inside the dddoc is still required and isolate and move that to dox?

**Comment by kdmurray91** [comment] 2016-09-19 03:51
@h-2 That information would be extremely useful. We currently just exclude this files from our packages, and do not attempt to build any documentation. We would be very keen to have documentation in the archives.

**Comment by xenigmax** [comment] 2016-09-19 07:52
@h-2 Unfortunately, I can't do that until October. But if nobody wants to do that, I will be working on it in November.

**Comment by kdmurray91** [comment] 2016-09-20 04:16
@xenigmax Sure, this isn't super urgent. Seqan is now in debian (unstable) as `libseqan2-dev`. We keep the old V1 headers around as `seqan-dev` as many programs use V1 still.

**Comment by h-2** [comment] 2016-09-20 10:35
@kdmurray91 thanks a lot, that's really great to see! A quick question: To me it looks like the pkgconfig file and the Cmake file are not included. Was this done on purpose?

**Comment by kdmurray91** [comment] 2016-09-20 23:12
Nope, that was accidental. @satta has plans to fix that. We also need to ensure that seqan-dev and libseqan2-dev are co-installable (don't provide the same files/directories). Any tips on this?

**Comment by mr-c** [comment] 2016-09-21 06:09
Kevin, they don't need to be co-installable but one has to be marked in
conflict with the other.

Pe 21 sept. 2016 2:12 a.m., "Kevin Murray" <notifications@github.com> a
scris:

**Comment by satta** [comment] 2016-09-21 09:33
Well, according to Debian's policy 7.4 [1] just marking packages with `Conflicts` is usually not the best solution, and it might help exploring other options. Can you think of a reasonable case where one would want both versions of SeqAn installed in `/usr/include/seqan` at the same time? If not, I'd say setting `Conflicts` is OK.

@h-2 While packaging Lambda I have prepared some additions to the `libseqan2-dev` package to include the CMake stuff as well, to a level that allowed the Lambda CMake config to detect SeqAn's presence (see https://github.com/seqan/lambda/issues/64). I'll update the package soon to include them. 

[1] https://www.debian.org/doc/debian-policy/ch-relationships.html

**Comment by h-2** [comment] 2016-09-21 10:53
> We also need to ensure that seqan-dev and libseqan2-dev are co-installable (don't provide the same files/directories). Any tips on this?

Unfortunately there is no clean way to do this. For the (distant) future SeqAn3 we will switch to `include/seqan3` and also namespace seqan3 so that it can coexist peacefully with SeqAn2, but for 2.x and 1.x this is not possible.

> Can you think of a reasonable case where one would want both versions of SeqAn installed in `/usr/include/seqan` at the same time? If not, I'd say setting Conflicts is OK.

Since seqan is always used as a build dependency only, I don't think this scenario exists. If debian packaging works like other systems I am more familiar with, this means that no binary pacakge every pulls in libseqan2-dev and the conflict never actually hits a user.

**Comment by satta** [comment] 2016-09-21 11:04
Thanks @h-2 for the reply. It looks like marking them as conflicting (and thus mutually exclusive) will be sufficient.

**Comment by satta** [comment] 2016-09-23 12:59
Just one more question from a CMake non-expert: how does one build the `.pc` file from the `.pc.in`? I'd like to include it in the -dev package but apparently it doesn't get populated with the versions and paths by default?

**Comment by h-2** [comment] 2016-09-23 13:12
@satta The configuring of the pc-file happens via cmake (although ultimately the pc file is of course completely unrelated to cmake) if the target ist SEQAN_RELEASE_LIBRARY which is the procedure that it is used for creating the "library tarballs" -- I told you it would be easier to use those :wink:

I really don't know how pkgconfig works, but likely you can do some regexing on the file. Maybe the relevant parts of the cmake file help:
 https://github.com/seqan/seqan/blob/master/util/cmake/SeqAnBuildSystem.cmake#L351
(to see how the file should look in the end, just look at the library tarballs)

**Comment by satta** [comment] 2016-09-23 14:31
@h-2 Thanks!

**Comment by h-2** [comment] 2016-09-27 23:21
@satta Thanks for the lambda port! Concerning the Seqan pacage: I have just looked at the package again, and now I see that the entire cmake folder is included. This should not be necessary, only the FindSeqAn.cmake file is required for cmake-based projects to find SeqAn. The exception to this are the official apps in our repo, they need the complete dir -- so actually the app-specific cmake things and the library specific cmake things are currently mixed in our repository which is an unfortunate legacy of previous versions :disappointed: 
Third party applications should only require `FindSeqAn.cmake` if they use cmake and only `seqan-2.pc` if they use pkgconfig. However the cmake-file should also be dropped into the `Modules` subdirectory of **cmake** not SeqAn. Otherwise packages will likely have to be patched to find it. (Did you do that for lambda?)
This is described here:
https://cmake.org/Wiki/CMake:How_To_Find_Libraries#How_package_finding_works

>  First CMake checks all directories in ${CMAKE_MODULE_PATH}, then it looks in its own module directory <CMAKE_ROOT>/share/cmake-x.y/Modules/.

For an example, see the packaging list on FreeBSD:
https://svnweb.freebsd.org/ports/head/biology/seqan/pkg-plist?revision=422156&view=markup#l674
On Debian it would be `/usr/share/cmake-3.x/Modules` I think.

**Comment by h-2** [comment] 2016-09-28 12:40
@satta @mr-c 
I am moving the general discussion about the debian packages to #1861 and will keep this issue about the dddoc/dox if thats ok.

**Comment by satta** [comment] 2016-09-29 08:13
Hi @h-2, thanks for opening a new issue for that! I'm a little busy at the moment but will take a closer look once things settle a bit.

**Comment by xenigmax** [comment] 2016-11-01 11:26
**1.  javascripts  / flashes**
The flash files are for the clipboard function.
There is a "copy permalink to clipboard" function in our dox system.
(Just visit http://docs.seqan.de/seqan/2.2.0/ and click any title like "home", "getting started")
This function is dependent on flash.

Other javascripts are also necessary for the fancy UIs of dox.
So the entire removal of those flash/javascripts can be a big decision.
-- It will disable newly added features like "tree-view" as well.

**2. dddoc / dox**
Unfortunately, dox uses dddoc as @rrahn said.
For examples, dddoc provides some function for parsing comments in source codes(.c/cpp/.h ..)
That means dddoc is not just a legacy code that can be removed simply.

There can be some redundancy between two.
And maybe we can make the codes more concise and maintainable.
However, this is clearly not a 1 day job and needs significant efforts.

So I would like to ask whether it's worthwhile to do since we can't remove javascript/flashes anyway because of 1.

@h-2 What is your opinion?

**Comment by h-2** [comment] 2016-11-01 11:42
> 1. javascripts / flashes

Concerning flash: it is apparently used for clipboard acces, can we replace it with https://clipboardjs.com/?
dropping clipboard functionality on old browsers is ok

@kdmurray91 concerning minified javascript: what does debian do in other cases where something uses jquery? Some of the stuff we might be able to get rid of, but certainly not all of it,,

> 2. dddoc / dox

We shouldn't spend too much time on this as we might switch to a different system fro SeqAn3. So we should focus on minimal changes that make the distributions happy...

**Comment by xenigmax** [comment] 2016-11-02 17:34
@h-2  The link you gave me uses HTML5 instead of flash. That means old browsers can't use this function. If it's the decision, that's OK. I can change them.

Regarding minified javascripts, maybe there is a way for a popular project like jquery..
But I'm not sure about the others. For example,
https://github.com/seqan/seqan/blob/master/util/py_lib/seqan/dox/tpl/js/less.min.js
https://github.com/seqan/seqan/blob/master/util/py_lib/seqan/dox/tpl/lib/bootstrap-multiselect/js/knockout-2.3.0.js

**Comment by kdmurray91** [comment] 2016-11-04 03:56
Minified JS is considered "compiled output" by the DFSG. Personally, for my own projects, I just dump the full source in there. That way debian et al. can either remove and replace with distro-wide installs of the JS source/min, or accept that as a package-specific embedded source. But what we can't do is package minified JS as an embedded copy, in the same way we couldn't do that with a SHLIB or ELF.

**Comment by h-2** [comment] 2016-11-08 11:51
@kdmurray91 Yes, that makes sense. It's simply not the preferred form of making changes to it, i.e. not the source.  @xenigmax Can you replace the minified js with non-minified js? Does this have any impact on performance?

**Comment by xenigmax** [comment] 2016-11-09 13:40
@h-2 
I think performance is not a big issue. As far as I know, the primary purpose of the minified .js is size reduction. However, I  have to check whether I can change them completely first since I'm not the original author and has limited knowledge about js. 

And.. I  have some fundamental question. I assume that you don't have enough time for thinking about this because you have to manage so many things. So hope you can consider below before making a decision.

*1) Are there many people who want to keep documents in local?*
I think most of the people only use the online version. Isn't it? If it is not, why don't we just **remove** them from the official repository instead of supporting compatibility and needs for packaging?
The separation of package.seqan.de is a good example. https://github.com/seqan/packages.seqan.de

I think the same question is relevant to tutorials. I assume that not many people wish to build HTML pages for the tutorial with python scripts like us. I think this decision make all of us happier including users who got trouble in build_dox(#1482),  and the package maintainer(probably?).

*2) Do you wish to use this in-house documentation system for Seqan3*
I assume that we will make 2 more releases at most for seqan2. But the efforts for replacing flashes and javascripts are only relevant to seqan2 if you don't want to use this in-house scripts anymore.

If you think it's important despite those questions, I will make 2 separate issues and do it.  - One for applying HTML5 instead of flash, and one for replacing minified .js. 

Please feel free to decide. :)

**Comment by xenigmax** [comment] 2016-11-09 15:33
@rrahn 
Frankly, I can't imagine a scenario that somebody needs API docs in local. But I will convince myself that there is a bioinformatician / computational biologist who has to work in offline. However, if we wish to keep this policy, we have to make docs **really simple** so that it works smoothly with any browsers / os / packaging policies. Or we have to take care of so many HTML/Javascript issues and this is clearly not the number one priority for sequence analysis library. Currently, we are supporting many OSs and compilers which is really good I think. However, we may not  want to add **multiple web browsers with different versions** in our supporting list. I think we can't do this.
https://www.google.co.kr/?gws_rd=ssl#q=+browser+compatibility+issue
So hope you can consider this fact when planning seqan3. I think that's enough.

Regarding the tutorials(not API), I was failed to convince myself that there is a user who wants to build HTML with our in-house python script instead of just visiting readthedocs. Please let me know if there is a reason that I don't know. I would like to ask you consider removing those from the official repository to be free from the compatibility issues regarding **python version**.

**Comment by h-2** [comment] 2016-11-09 15:33
> why don't we just remove them from the official repository

We will for SeqAn3, but not anymore for SeqAn2, because it would change too many workflows.

> 2) Do you wish to use this in-house documentation system for Seqan3

Most probably not.

> If you think it's important despite those questions, I will make 2 separate issues and do it. - One for applying HTML5 instead of flash, and one for replacing minified .js.

Yes, please!  I think we need to get it done, because SeqAn3 will probably not see its first release before 2017Q4 and SeqAn2 will be used for a long while. Apps still use SeqAn1 :fearful:

**Comment by h-2** [comment] 2016-11-09 15:35
PS: we won't worry more about compatibility, this is just to satisfy legal requirement of downstream distributions...

**Comment by xenigmax** [comment] 2016-11-09 15:53
Does removing docs affect workflows? I didn't know that. I don't want to make the situation more complex.
We already have encountered several compatibility problems(malfunction, broken layout) when modifying javascript / HTMLs. I'm just afraid that kind of situation.

**Comment by kdmurray91** [comment] 2016-11-09 23:50
@xenigmax FWIW I extensively use offline API docs, as the internet where I often code is abysmal. That doesn't really require having everything in one repo though, so long as I can build a `libseqan2-doc` package :).

**Comment by xenigmax** [comment] 2016-11-10 15:37
I just made 2 pull requests regarding this.  >130 files were affected. 

I've tested them with Chrome / Firefox in Debian.
However, I assume that there are more issues after this change which I can't reproduce.

So please feel free to let me know if you see something weird with your OS / browser version.

**Comment by xenigmax** [comment] 2016-11-10 15:42
@kdmurray91  First of all, thank you for reporting us this issue. Many of the team members use Debian and it would be really cool if we can ship SeqAn to some official repositories.

I raised some question since current dox system is too hard to maintain for us. SeqAn3 may use simpler one and it will solve all the problem. Thank you for your effort about the packaging, again!

**Comment by h-2** [comment] 2016-11-10 16:22
@kdmurray91 we have merged the removal of flash, but before merging the "un"-minifiying PR, I would like to double-check that this actually fulfills the requirements for debian. Could you please have a look? Thanks!

**Comment by h-2** [comment] 2016-11-21 18:24
@kdmurray91 polite ping as we want to get 2.3.0 out the door. This is the PR: #1937

**Comment by kdmurray91** [comment] 2016-11-23 01:30
@h-2 Sorry for the slow response. AFAICT, the policy of debian is now satisfied. We will either replace embedded full JS sources with symlinks to debian packaged versions ([per this lintian error](https://lintian.debian.org/tags/embedded-javascript-library.html)), or package the full sources.  This will be fine so long as all the JS sources are freely licensed. I'm unable to check that in the diff from here, as the internet is so slow I'm unable to load the (rather large) diff. If it turns out there are any non-free sources, we'll deal with that later (FTPMASTER will have to check each source file before the doc package makes it to unstable).

**Comment by h-2** [comment] 2016-11-23 10:33
@kdmurray91 no problem, thanks for the feedback, I have merged the PR!

**Comment by h-2** [comment] 2016-11-23 10:34
I am closing this issue because all legal issues regarding inclusion into debian should be resolved now.

**Closed by h-2** 2016-11-23 10:33 UTC
Labels: dox
